#!/usr/bin/env zsh
# ais_help_ops — AIStudio operator command reference (not for end users)

echo ""
echo "+==============================================================+"
echo "|              AIStudio — Operator Commands                    |"
echo "+==============================================================+"
echo ""
echo "── Application ──────────────────────────────────────────────"
echo "  ais_start          Start all services (Qdrant, Ollama, FastAPI, opens UI)"
echo "  ais_stop           Stop all services"
echo ""
echo "── Corpus & Data ────────────────────────────────────────────"
echo "  ais_sec_download   Download SEC 10-K corpus from EDGAR (~500MB)"
echo ""
echo "── Benchmarking ─────────────────────────────────────────────"
echo "  ais_bench          Run benchmark on demo corpus (default settings)"
echo ""
echo "── Development ──────────────────────────────────────────────"
echo "  ais_test           Run unit tests (make test)"
echo "  ais_check          Run lint + unit tests (make check)"
echo "  ais_deploy <file>  Deploy file from ~/Downloads to correct location"
echo "                     Handles tracked, gitignored, and meta/ files"
echo "                     Destination auto-discovered from bundle_manifest.yaml"
echo "  ais_commit <msg>   git add -A (guarded) + commit + push"
echo "  ais_publish <f> <msg>  ais_deploy + ais_commit in one shot"
echo ""
echo "── EOS ──────────────────────────────────────────────────────"
echo "  ais_packet         Generate session PACKET → ~/Downloads"
echo "  ais_bundle         Persist PACKET + BUNDLE to meta/, git commit"
echo "                     Also copies BUNDLE to ~/Downloads as backup"
echo ""
echo "── Recovery ─────────────────────────────────────────────────"
echo "  ais_restore_scripts  Restore operator scripts from latest BUNDLE zip"
echo "                       Run after git filter-repo wipes scripts/"
echo ""
echo "── Help ─────────────────────────────────────────────────────"
echo "  ais_help           User command reference"
echo "  ais_help_ops       This reference (operator)"
echo ""
echo "Docs: see meta/reference/HOWTO_OPS.md for full operator guide"
echo ""
