#!/usr/bin/env zsh
# ais_help — AIStudio command reference
# Prints all ais_* aliases and functions with descriptions.
# Place in: ~/Developer/AIStudio/scripts/
# Add alias to ~/.zshrc: alias ais_help='~/Developer/AIStudio/scripts/ais_help.sh'

echo ""
echo "+==============================================================+"
echo "|              AIStudio — Command Reference                    |"
echo "+==============================================================+"
echo ""
echo "── Application ──────────────────────────────────────────────"
echo "  ais_start          Start all services (Qdrant, Ollama, FastAPI, UI)"
echo "  ais_stop           Stop Qdrant and FastAPI (leaves Ollama running)"
echo ""
echo "── Development ──────────────────────────────────────────────"
echo "  ais_test           Run full test suite (make test)"
echo "  ais_check          Run lint + unit tests — mirrors CI (make check)"
echo "  ais_bench          Run benchmark on demo corpus (default settings)"
echo "  ais_sec_download   Download SEC 10-K corpus from EDGAR"
echo ""
echo "── Deployment ───────────────────────────────────────────────"
echo "  ais_deploy <file>  Copy file from ~/Downloads to repo, run lint"
echo "                     Auto-discovers destination: manifest → repo → .deploy_map"
echo "                     Handles macOS (N) suffix automatically"
echo "  ais_commit <msg>   git add -A && commit && push"
echo "  ais_publish <file> <msg>  ais_deploy + ais_commit in one shot"
echo ""
echo "── EOS (End of Session) ─────────────────────────────────────"
echo "  ais_packet         Generate session PACKET → ~/Downloads"
echo "  ais_bundle         Persist PACKET + BUNDLE to meta/, git commit"
echo "                     Always run AFTER reviewing the PACKET"
echo ""
echo "── Meta ─────────────────────────────────────────────────────"
echo "  ais_help           Show this reference"
echo ""
echo "Usage notes:"
echo "  - Always download files from Claude left pane before ais_deploy"
echo "  - ais_deploy handles meta/ (gitignored) and repo files transparently"
echo "  - EOS sequence: ais_packet → review → ais_bundle (never skip review)"
echo ""
