#!/usr/bin/env zsh
# ais_ingest_sec_10k.sh — Ingest the SEC 10-K corpus into AIStudio
# Version: 1.3.4
# Changelog:
#   1.3.2 — AIStudio_673: Populate --- Setup section with effective config defaults.
#           Ingest summary now shown as human-readable table (via __main__.py).
#           Raw JSON output moved to --verbose flag in __main__.py.
#   1.3.4 — Move --- Important above --- Ingesting per STD §8.
#   1.3.4 — Fix zsh "unmatched quote" error: use ${FORCE_FLAG:+--force} expansion.
#   1.3.3 — STD §8 minimal compliance: wording fixes, --- Important section,
#           ▶ line with · separators + ellipsis, --force flag, --- Next steps.
#   1.3.1 — Wrap ingest with caffeinate -i to prevent macOS sleep during long runs.
#           Updated "leave terminal open" message to clarify "minimized but not closed."
#           Hardware-aware time estimate: Pro vs Air.
#   1.3.0 — Questions YAML v2.0.0: 8 retail-bank-trends questions (cross-firm + temporal)
#   1.2.4 — Heredoc YAML fixes for sec_10k corpus_metadata (25 firms x 5 filings target)
#   1.2.2 — Initial 1.2.x baseline
#   1.2.0 — auto-generate sec_10k_corpus_metadata.yaml on first run (schema v1.0)
#   1.1.0 — auto-generate sec_10k_questions.yaml on first run
# Ingests all .htm files from data/corpora/sec_10k/uploads/ into the sec_10k corpus.
# Requires: AIStudio backend running (ais_start) and files downloaded (ais_download_sec_10k)


# ── Source guard: this script must be executed, not sourced ──────────────────
[[ "$ZSH_EVAL_CONTEXT" == *:file* ]] && { echo "❌ Do not source this script — execute it directly."; return 1; }

VERSION="1.3.4"

SCRIPT_NAME="ais_ingest_sec_10k"
REPO="${0:A:h}"
HELP_FILE="$REPO/ais_command_help.txt"

_show_help() {
    if [[ -f "$HELP_FILE" ]]; then
        awk "/^## $SCRIPT_NAME$/,/^---$/" "$HELP_FILE" | grep -v "^---$" | grep -v "^## "
    else
        echo "$SCRIPT_NAME v$VERSION"
        echo ""
        echo "Usage: $SCRIPT_NAME [--help] [--version]"
        echo ""
        echo "Run from: ~/Developer/AIStudio"
    fi
}

if [[ "$1" == "--help" ]]; then _show_help; exit 0; fi
if [[ "$1" == "--version" ]]; then echo "$SCRIPT_NAME v$VERSION"; exit 0; fi

API="http://localhost:8000"
UPLOADS="$REPO/data/corpora/sec_10k/uploads"
BENCH_DIR="$REPO/benchmarks/sec_10k"
CORPUS_DIR="$REPO/data/corpora/sec_10k"

printf "\033[1m[ais_ingest_sec_10k v$VERSION — Ingest SEC 10-K corpus]\033[0m\n"

# --- Preflight
echo "--- Preflight"

if [[ ! -d "$UPLOADS" ]]; then
    echo "❌ Source directory not found: data/corpora/sec_10k/uploads/"
    echo "· Run: ais_download_sec_10k"
    exit 1
fi

FILE_COUNT=$(ls "$UPLOADS"/*.htm 2>/dev/null | wc -l | tr -d ' ')
if [[ "$FILE_COUNT" -eq 0 ]]; then
    echo "❌ No .htm files found in data/corpora/sec_10k/uploads/"
    echo "· Run: ais_download_sec_10k"
    exit 1
fi
echo "✅ $FILE_COUNT filings ready."

if ! curl -sf "$API/health" > /dev/null 2>&1; then
    echo "❌ Backend not reachable at $API"
    echo "· Run: ais_start"
    exit 1
fi
echo "✅ Backend healthy."

# --- Setup
echo ""
echo "--- Setup"
echo "· Corpus     : sec_10k (25 firms × 5 filings target)"
echo "· Chunk size : 1200 chars · Overlap: 200 chars"
echo "· Embed model: nomic-embed-text"
echo "· Normalizer : Document-Head Extraction + Temporal Context Injection (pipeline.py v1.7.0)"
echo "· Source     : $UPLOADS"

# Create benchmarks/sec_10k/ on first run
if [[ ! -d "$BENCH_DIR" ]]; then
    mkdir -p "$BENCH_DIR/reports"
    echo "✅ Created benchmarks/sec_10k/ with reports/ subfolder."
fi

# Write sec_10k_questions.yaml on first run
QUESTIONS_FILE="$BENCH_DIR/sec_10k_questions.yaml"
if [[ ! -f "$QUESTIONS_FILE" ]]; then
    cat > "$QUESTIONS_FILE" << 'EOF'
# AIStudio — SEC 10-K Corpus Benchmark Questions
# Version: 2.0.0
# Auto-generated by ais_ingest_sec_10k on first run
# Corpus: sec_10k — multi-firm financial services corpus
# Focus: Cross-firm retail banking trends and temporal evolution over 5 fiscal years

- topic: AI Risk Evolution
  questions:
    - id: ai_disclosure_evolution
      question: How has AI risk disclosure evolved at major US retail banks from 2022 to 2026? Compare what JPMorgan, Bank of America, and Wells Fargo say about AI risks, and identify which firm started disclosing AI risks earliest.
      keywords: [AI, artificial intelligence, risk, disclosure]
      notes: Cross-firm + temporal trend question — tests retrieval across multiple firms and years

    - id: ai_governance_committees_comparison
      question: Which of JPMorgan, Bank of America, Wells Fargo, or Citigroup have established dedicated AI governance committees, and how do their oversight structures differ?
      keywords: [AI, governance, committee, oversight]
      notes: Cross-firm comparison of governance structures

- topic: Cybersecurity & Operational Risk
  questions:
    - id: cyber_disclosure_2022_vs_2026
      question: Compare how retail banks describe their cybersecurity risk management framework in their 2022 versus 2026 annual reports. What concrete changes in oversight, governance bodies, or response procedures have emerged?
      keywords: [cybersecurity, risk management, governance]
      notes: Temporal comparison — 2022 vs 2026 across retail banks

- topic: Climate & Environmental Risk
  questions:
    - id: climate_risk_evolution
      question: How has climate risk disclosure language and depth evolved in retail bank 10-K filings since 2022? Which firm has the most detailed Net Zero or transition risk framework?
      keywords: [climate, transition risk, Net Zero, sustainability]
      notes: Cross-firm + temporal — climate disclosure has been a major regulatory focus area

- topic: Capital & Financial Position
  questions:
    - id: capital_ratios_trend
      question: How have CET1 capital ratios and total revenues trended at JPMorgan, Bank of America, Wells Fargo, and Citigroup from FY2021 through FY2025? Identify any consistent leaders or laggards.
      keywords: [CET1, capital ratio, revenue, billion]
      notes: Tests financial data extraction across firms and years — must NOT trigger refusal

- topic: Digital Banking & Technology
  questions:
    - id: digital_banking_strategy
      question: How have major retail banks described their digital banking strategy and technology investment priorities over the last 5 years? What major themes emerge across firms?
      keywords: [digital, technology, investment, mobile, online]
      notes: Cross-firm + temporal — digital transformation is a sector-wide theme

- topic: Regulatory & Macro Environment
  questions:
    - id: regulatory_burden_evolution
      question: What new regulatory burdens, capital rules, or compliance requirements have retail banks disclosed in their 2025 and 2026 filings compared to 2022? Are there themes that all firms agree are most challenging?
      keywords: [regulation, capital rules, compliance, Basel]
      notes: Tests recent regulatory disclosures and consensus across firms

- topic: Latency Baseline
  questions:
    - id: latency_test
      question: What is the primary business of the firms in this corpus?
      keywords: [bank, financial, services]
      notes: Simple corpus-grounded query for latency baseline measurement
EOF
    echo "✅ Created benchmarks/sec_10k/sec_10k_questions.yaml"
fi

# Write sec_10k_corpus_metadata.yaml on first run
METADATA_FILE="$CORPUS_DIR/sec_10k_corpus_metadata.yaml"
if [[ ! -f "$METADATA_FILE" ]]; then
    mkdir -p "$CORPUS_DIR"
    cat > "$METADATA_FILE" << 'EOF'
# sec_10k_corpus_metadata.yaml
# Corpus metadata — loaded by api.py at query time
# Auto-generated by ais_ingest_sec_10k on first run

schema_version: "1.0"
corpus_name: sec_10k
short_description: "Up to 125 SEC 10-K filings — 25 major financial services firms"
description: >-
  Annual report (10-K) filings from 25 major financial services firms downloaded
  from SEC EDGAR. Covers bulge-bracket banks, asset managers, exchanges, and
  custody banks. Filings span multiple years — use the Year filter to restrict
  retrieval to a specific filing period.
content_summary: >-
  Filings from 25 firms: bulge-bracket banks (Goldman Sachs, JPMorgan Chase,
  Morgan Stanley, Bank of America, Citigroup, Wells Fargo), asset managers
  (BlackRock, T. Rowe Price, Franklin Templeton, Invesco, AllianceBernstein),
  exchanges (CME Group, ICE, Nasdaq, CBOE), insurance (AIG, MetLife, Prudential,
  Travelers), custody (BNY Mellon, State Street, Northern Trust), and boutiques
  (Jefferies, Raymond James, Stifel Financial).
search_guidance: |
  Route questions to the most relevant firm and filing year:
  - Always use the Firm filter for firm-specific questions (e.g. "Goldman Sachs")
  - Always use the Year filter for year-specific questions (e.g. "2023")
  - AI risk, AI governance committees → Goldman Sachs, JPMorgan Chase, Morgan Stanley
  - Cybersecurity risk management → JPMorgan Chase, Bank of America, Citigroup
  - Model risk governance → Morgan Stanley, Goldman Sachs
  - Climate risk, ESG → Bank of America, Citigroup, Wells Fargo
  - Revenue and financials → use Year filter + firm name for precision
  - Cross-firm comparisons → leave Firm filter blank, use Year filter only
  When no firm filter is set, answers may blend content from multiple firms.
  The CrossEncoder reranker improves precision — but firm-specific queries benefit
  significantly from the Firm filter applied at the vector layer.
EOF
    echo "✅ Created data/corpora/sec_10k/sec_10k_corpus_metadata.yaml"
fi

# --- Ingesting
echo "--- Important"
echo "· This terminal can be minimized but should not be closed."
echo "· Sleep prevention: caffeinate -i is active for the duration."
echo "--- Ingesting"
echo "▶ Ingesting $FILE_COUNT filings · ~35 min on M4 Pro · ~90 min on M4 Air..."

# Parse --force flag
FORCE_FLAG=""
for arg in "$@"; do
    [[ "$arg" == "--force" ]] && FORCE_FLAG="--force"
done

cd "$REPO"
source .venv/bin/activate
caffeinate -i env AISTUDIO_VECTORSTORE=qdrant PYTHONPATH=src \
    python3 -m local_llm_bot.app.ingest \
    --corpus sec_10k \
    --root "$UPLOADS" ${FORCE_FLAG:+--force}

echo "--- Next steps"
echo "✅ Corpus 'sec_10k' ready."
echo "· Select 'sec_10k' in the AIStudio corpus dropdown to query."
echo "· To benchmark : ais_bench --corpus sec_10k"
echo "· To re-ingest : $SCRIPT_NAME --force"
