#!/usr/bin/env zsh
# ais_help — AIStudio user command reference

echo ""
echo "+==============================================================+"
echo "|              AIStudio — Command Reference                    |"
echo "+==============================================================+"
echo ""
echo "── Setup ────────────────────────────────────────────────────"
echo "  ais_install        Install AIStudio — run once after cloning"
echo ""
echo "── Application ──────────────────────────────────────────────"
echo "  ais_start          Start all services (Qdrant, Ollama, FastAPI, opens UI)"
echo "  ais_stop           Stop all services"
echo "  ais_restart        Stop then restart all services"
echo ""
echo "── Corpus & Data ────────────────────────────────────────────"
echo "  ais_sec_download   Download SEC 10-K corpus from EDGAR (~500MB)"
echo ""
echo "── Benchmarking ─────────────────────────────────────────────"
echo "  ais_bench          Run benchmark on demo corpus (default settings)"
echo ""
echo "── Development ──────────────────────────────────────────────"
echo "  ais_test           Run unit tests (make test)"
echo "  ais_check          Run lint + unit tests (make check)"
echo "  ais_deploy <file>  Deploy file from ~/Downloads to correct location"
echo "                     Handles tracked, gitignored, and meta/ files"
echo "                     Destination auto-discovered from bundle_manifest.yaml"
echo ""
echo "── Recovery ─────────────────────────────────────────────────"
echo "  ais_restore_scripts  Restore operator scripts from latest BUNDLE zip"
echo "                       Run after git filter-repo wipes scripts/"
echo ""
echo "── Help ─────────────────────────────────────────────────────"
echo "  ais_help           Show this reference"
echo ""
echo "Setup: bash ~/Developer/AIStudio/install.sh && source ~/.zshrc"
echo "Docs:  see QUICKSTART.md for full getting-started guide"
echo ""
