#!/usr/bin/env zsh
# ais_help — AIStudio user command reference
# Version: 1.1.0

echo ""
echo "+==============================================================+"
echo "|              AIStudio — Command Reference                    |"
echo "+==============================================================+"
echo ""
echo "── Setup ────────────────────────────────────────────────────"
echo "  ais_install           Install AIStudio — run once after cloning"
echo "  ais_install <cmd>     Install a single command alias"
echo "  ais_install --verify  Verify all command aliases are active"
echo ""
echo "── Application ──────────────────────────────────────────────"
echo "  ais_start             Start all services (Qdrant, Ollama, FastAPI, opens UI)"
echo "  ais_stop              Stop all services"
echo "  ais_log               Tail live backend log (run in separate tab)"
echo ""
echo "── Corpus & Data ────────────────────────────────────────────"
echo "  ais_download_sec_10k  Download SEC 10-K corpus from EDGAR (~2GB)"
echo "  ais_ingest_sec_10k    Ingest SEC 10-K corpus (~30 min, backend required)"
echo ""
echo "── Benchmarking ─────────────────────────────────────────────"
echo "  ais_bench             Run benchmark on demo corpus (default settings)"
echo ""
echo "── Help ─────────────────────────────────────────────────────"
echo "  ais_help              Show this reference"
echo ""
echo "Setup: cd ~/Developer/AIStudio && ./ais_install"
echo "Docs:  see QUICKSTART.md for full getting-started guide"
echo ""
