#!/usr/bin/env zsh
# ais_ingest_sec_10k.sh — Ingest the SEC 10-K corpus into AIStudio
# Version: 1.1.0
# Ingests all .htm files from data/corpora/sec_10k/uploads/ into the sec_10k corpus.
# Requires: AIStudio backend running (ais_start) and files downloaded (ais_download_sec_10k)

VERSION="1.1.0"
REPO="$(cd "$(dirname "$0")" && pwd)"
API="http://localhost:8000"
UPLOADS="$REPO/data/corpora/sec_10k/uploads"
BENCH_DIR="$REPO/benchmarks/sec_10k"

printf "\033[1m[ais_ingest_sec_10k v$VERSION — Ingest SEC 10-K corpus]\033[0m\n"

if [[ "$1" == "--version" ]]; then
    exit 0
fi

if [[ "$1" == "--help" ]]; then
    echo ""
    echo "Usage: ais_ingest_sec_10k"
    echo ""
    echo "Ingests SEC 10-K filings into AIStudio as the 'sec_10k' corpus."
    echo ""
    echo "Requirements:"
    echo "  1. AIStudio must be running: ais_start"
    echo "  2. Filings must be downloaded: ais_download_sec_10k"
    echo ""
    echo "· Source: data/corpora/sec_10k/uploads/"
    echo "· ⏱  Expected time: ~30 minutes on M4 MacBook Pro"
    echo "· 143 filings · 25 firms · ~106,000 chunks"
    exit 0
fi

# --- Preflight
echo "--- Preflight"

if [[ ! -d "$UPLOADS" ]]; then
    echo "❌ Source directory not found: data/corpora/sec_10k/uploads/"
    echo "· Run: ais_download_sec_10k"
    exit 1
fi

FILE_COUNT=$(ls "$UPLOADS"/*.htm 2>/dev/null | wc -l | tr -d ' ')
if [[ "$FILE_COUNT" -eq 0 ]]; then
    echo "❌ No .htm files found in data/corpora/sec_10k/uploads/"
    echo "· Run: ais_download_sec_10k"
    exit 1
fi
echo "✅ $FILE_COUNT filings ready."

if ! curl -sf "$API/health" > /dev/null 2>&1; then
    echo "❌ Backend not reachable at $API"
    echo "· Run: ais_start"
    exit 1
fi
echo "✅ Backend healthy."

# --- Setup
echo ""
echo "--- Setup"

# Create benchmarks/sec_10k/ on first run
if [[ ! -d "$BENCH_DIR" ]]; then
    mkdir -p "$BENCH_DIR/reports"
    echo "✅ Created benchmarks/sec_10k/ with reports/ subfolder."
fi

# Write sec_10k_questions.yaml on first run
QUESTIONS_FILE="$BENCH_DIR/sec_10k_questions.yaml"
if [[ ! -f "$QUESTIONS_FILE" ]]; then
    cat > "$QUESTIONS_FILE" << 'EOF'
# AIStudio — SEC 10-K Corpus Benchmark Questions
# Version: 1.0.0
# Auto-generated by ais_ingest_sec_10k on first run
# Corpus: sec_10k — 143 filings, 25 financial services firms

- topic: AI Risk and Governance
  questions:
    - id: goldman_ai_risk
      question: What does Goldman Sachs say about the risks of artificial intelligence?
      keywords: [artificial intelligence, AI, risk, Goldman]
      notes: Should return Goldman-specific AI risk disclosure

    - id: goldman_ai_committee
      question: Does Goldman Sachs have an AI governance committee and what does it do?
      keywords: [Artificial Intelligence, committee, governance]
      notes: Should mention Firmwide Artificial Intelligence Risk and Controls Committee

    - id: cross_corpus_ai_governance
      question: Which financial firms have dedicated AI governance committees?
      keywords: [AI, committee, governance]
      notes: No firm filter — tests cross-corpus retrieval quality

- topic: Cybersecurity
  questions:
    - id: jpmorgan_cybersecurity
      question: How does JPMorgan Chase describe their cybersecurity risk management?
      keywords: [cybersecurity, JPMorgan, risk]
      notes: Should return JPMorgan cybersecurity section

- topic: Model Risk
  questions:
    - id: morgan_stanley_model_risk
      question: What is Morgan Stanley's approach to model risk?
      keywords: [model risk, Morgan Stanley]
      notes: Should return model risk governance section

- topic: Climate Risk
  questions:
    - id: bofa_climate_risk
      question: How does Bank of America describe climate risk in their annual report?
      keywords: [climate, risk, Bank of America]
      notes: Should return climate risk section

- topic: Revenue and Financials
  questions:
    - id: goldman_2026_revenue
      question: What were Goldman Sachs total revenues in 2025?
      keywords: [revenue, billion, 2025]
      notes: Tests year filter combined with firm filter

- topic: Latency Baseline
  questions:
    - id: latency_test
      question: What is Goldman Sachs?
      keywords: [Goldman Sachs, bank, financial]
      notes: Simple query for latency baseline measurement
EOF
    echo "✅ Created benchmarks/sec_10k/sec_10k_questions.yaml"
fi

# --- Ingesting
echo ""
echo "--- Ingesting"
echo "▶ Ingesting $FILE_COUNT filings — this will take ~30 minutes..."
echo "· Leave this terminal open until complete."
echo ""

cd "$REPO"
source .venv/bin/activate
AISTUDIO_VECTORSTORE=qdrant PYTHONPATH=src \
    python3 -m local_llm_bot.app.ingest \
    --corpus sec_10k \
    --root "$UPLOADS"

echo ""
echo "--- Summary"
echo "✅ SEC 10-K corpus ingested."
echo "· Select 'sec_10k' in the AIStudio corpus dropdown."
echo "· To benchmark: ais_bench --corpus sec_10k"
