#!/usr/bin/env python3
"""
ais_import_entity_kb_ops.py — Build the entity knowledge base for a whole corpus (OPS).

Source is ALWAYS GLEIF (no --source). Operates over the WHOLE corpus (no --scope).

WORKSHEET ROUND-TRIP (the operator workflow):
  1. First run on a corpus: scan every filing in data/corpora/<corpus>/uploads/,
     extract each filing's self-reported XBRL name, take a best-guess GLEIF match
     for each, and write a per-corpus WORKSHEET:
         data/corpora/<corpus>/<corpus>_entity_worksheet.yaml
     One entry per distinct xbrl_name (with all its files, name-sorted), PLUS one
     entry per group of name-less files sharing their first 8 filename chars.
  2. Open the worksheet beside search.gleif.org. On any row whose gleif_canonical
     is wrong (sub / ADR / namesake) or blank, fill ONLY `lei_corrected` with the
     real 20-char LEI. For name-less groups, author an `xbrl_name` (preferred) or at
     least a `canonical` so the files can still be bound. Touch nothing else.
  3. Re-run (no flags): the worksheet is detected; rows with `lei_corrected` are
     refreshed deterministically via _fetch_gleif_by_lei (canonical/lei rewritten
     from that record); name-search guesses are cached, not re-fetched. Worksheet is
     rewritten with the refreshed values. Loop 2<->3 until the table is clean.
  4. --apply: build the real KB (gleif_<corpus>_full_entities.yaml, xbrl_name-keyed)
     from the corrected worksheet, enrich aliases, update the catalog.

  --rescan re-reads the uploads dir (new/removed files) and MERGES, preserving every
  human edit (lei_corrected + authored xbrl_name/canonical) by xbrl_name / group key.

Run via the wrapper (cd repo, venv) or directly:
    python3 scripts/ais_import_entity_kb_ops.py --corpus sec_10k            # scan -> worksheet
    python3 scripts/ais_import_entity_kb_ops.py --corpus sec_10k            # re-run -> consume edits
    python3 scripts/ais_import_entity_kb_ops.py --corpus sec_10k --apply    # write the KB

Changelog
  1.3.0 — Worksheet round-trip. The command now emits a per-corpus, human-editable
          worksheet (entries grouped by entity, files multi-valued + name-sorted,
          name-less files grouped by first-8-filename-chars) carrying the GLEIF
          guess + a `lei_corrected` field. Re-runs consume `lei_corrected` (and
          authored xbrl_name/canonical) and refresh deterministically by LEI. --apply
          builds the KB from the corrected worksheet. Per-entry alias lists are copied
          (no shared YAML anchors). Replaced the separate <corpus>_lei_hints.yaml.
          Added --rescan (merge new files, keep edits).
  1.2.1 — Cosmetic: ANSI clear-to-EOL on progress lines (no stray right-margin block).
  1.2.0 — Live scan progress counter (the bs4 parse phase was silent on ESEF).
  1.1.0 — Output conformed to STD - AIStudio - CLI Output v1.3.0 (sections + progress).
  1.0.0 — Initial split from ais_import_knowledge_base_ops.py.

Version: 1.3.0
"""

import argparse
import re
import sys
from pathlib import Path

import _kb_common_ops as kb  # shared library (underscore = not a command; no alias, install:none)
import yaml

VERSION = "1.3.0"
SCRIPT_NAME = "ais_import_entity_kb_ops"

# XBRL self-reported-name tags, in priority order (SEC, ESEF, UK GAAP).
_ENTITY_TAGS = [
    "dei:EntityRegistrantName",
    "ifrs-full:NameOfReportingEntityOrOtherMeansOfIdentification",
    "uk-gaap:EntityCurrentLegalOrRegisteredName",
]
_SCAN_SUFFIXES = (".htm", ".html", ".xhtml")
_GROUP_PREFIX_LEN = 8  # name-less files are grouped by their first N filename chars

_WORKSHEET_HEADER = """\
# {corpus}_entity_worksheet.yaml — generated by ais_import_entity_kb_ops.
#
# HOW TO USE (edit, then re-run the command on this corpus):
#  - Rows WITH an xbrl_name: check gleif_canonical against search.gleif.org. If it is
#    the wrong entity (subsidiary / ADR / namesake) or blank, put the real 20-char LEI
#    in `lei_corrected`. Touch nothing else - on re-run, lei_corrected is authoritative
#    and rewrites gleif_canonical / gleif_lei from that record.
#  - Rows with an EMPTY xbrl_name (name-less files, grouped by filename): give them an
#    identity so they can still be ingested - in order of preference, author an
#    `xbrl_name`, else at least a `canonical`. Add `lei_corrected` too if you know it.
#  - `files` is the full, name-sorted list of filings behind each entry. Do not edit it.
#
# Then: ais_import_entity_kb_ops --corpus {corpus}            (re-run to refresh)
#       ais_import_entity_kb_ops --corpus {corpus} --apply    (write the KB when clean)
"""


# -- XBRL-name extraction (own minimal reader; to be unified with pipeline later) --
def _extract_xbrl_name(path: Path) -> str | None:
    """Return the filing's self-reported entity name from its XBRL tag, or None."""
    try:
        text = path.read_text(errors="ignore")
    except Exception:
        return None

    # Preferred: BeautifulSoup (same library ingest uses) — robust to nested markup.
    try:
        from bs4 import BeautifulSoup
        soup = BeautifulSoup(text, "html.parser")
        for tag in _ENTITY_TAGS:
            el = soup.find(attrs={"name": tag})
            if el:
                val = " ".join(el.get_text(strip=True).split())
                if val:
                    return val
    except Exception:
        pass

    # Fallback: regex (no bs4). Captures inner text of the tag carrying name="<tag>".
    for tag in _ENTITY_TAGS:
        m = re.search(
            r'name="' + re.escape(tag) + r'"[^>]*>(.*?)</',
            text, re.IGNORECASE | re.DOTALL,
        )
        if m:
            val = re.sub(r"<[^>]+>", " ", m.group(1))
            val = " ".join(val.split())
            if val:
                return val
    return None


def _scan_corpus(corpus: str) -> tuple[dict[str, list[str]], list[str]]:
    """Scan data/corpora/<corpus>/uploads/. Return ({xbrl_name: [filenames]}, [name-less files])."""
    uploads = kb.REPO / "data" / "corpora" / corpus / "uploads"
    if not uploads.exists():
        raise FileNotFoundError(f"Corpus uploads dir not found: {uploads}")
    by_name: dict[str, list[str]] = {}
    no_name: list[str] = []
    files = sorted(p for p in uploads.iterdir()
                   if p.is_file() and p.suffix.lower() in _SCAN_SUFFIXES)
    total = len(files)
    for i, p in enumerate(files, 1):
        # Live progress — parsing large iXBRL files with bs4 is the slow phase.
        progress = f"  ▶ Scanning {i}/{total} — {p.name}"
        print("\r" + progress[:100] + "\033[K", end="", flush=True)
        name = _extract_xbrl_name(p)
        if name:
            by_name.setdefault(name, []).append(p.name)
        else:
            no_name.append(p.name)
    # Clear the progress line; the caller prints the scan summary.
    print("\r\033[K", end="", flush=True)
    return by_name, no_name


# -- Worksheet model -----------------------------------------------------------
def _worksheet_path(corpus: str) -> Path:
    return kb.REPO / "data" / "corpora" / corpus / f"{corpus}_entity_worksheet.yaml"


def _scan_to_entries(corpus: str) -> list[dict]:
    """Build worksheet entries from a fresh scan: named entries + name-less groups."""
    by_name, no_name = _scan_corpus(corpus)
    entries: list[dict] = []
    for xbrl_name in sorted(by_name):
        entries.append({
            "xbrl_name": xbrl_name,
            "files": sorted(by_name[xbrl_name]),
            "gleif_canonical": None,
            "gleif_lei": None,
            "lei_corrected": None,
        })
    groups: dict[str, list[str]] = {}
    for f in no_name:
        groups.setdefault(f[:_GROUP_PREFIX_LEN], []).append(f)
    for key in sorted(groups):
        entries.append({
            "xbrl_name": None,           # EMPTY — author an xbrl_name (or canonical)
            "group_key": key,
            "canonical": None,
            "files": sorted(groups[key]),
            "gleif_canonical": None,
            "gleif_lei": None,
            "lei_corrected": None,
        })
    return entries


def _entry_key(e: dict) -> str:
    """Stable key for merging edits across rescans."""
    return e.get("xbrl_name") or f"group:{e.get('group_key', '')}"


def _merge_edits(fresh: list[dict], old: list[dict]) -> list[dict]:
    """Carry human edits (lei_corrected + authored xbrl_name/canonical + cached guess)
    from an existing worksheet onto a freshly-scanned set, keyed by entry key."""
    old_by_key = {_entry_key(e): e for e in old}
    for e in fresh:
        prev = old_by_key.get(_entry_key(e))
        if not prev:
            continue
        for fld in ("lei_corrected", "canonical", "gleif_canonical", "gleif_lei"):
            if prev.get(fld):
                e[fld] = prev[fld]
        # A name-less group the operator already named: carry the authored name.
        if e.get("xbrl_name") is None and prev.get("xbrl_name"):
            e["xbrl_name"] = prev["xbrl_name"]
    return fresh


def _load_worksheet(path: Path) -> list[dict]:
    with open(path) as f:
        data = yaml.safe_load(f) or {}
    return data.get("entries", []) or []


def _write_worksheet(corpus: str, path: Path, entries: list[dict]) -> None:
    # `status` is transient (recomputed every run) — keep it out of the saved file.
    clean = [{k: v for k, v in e.items() if k != "status"} for e in entries]
    body = {
        "schema_version": "1.0",
        "kind": "entity_worksheet",
        "corpus": corpus,
        "generated": kb.datetime.now().strftime("%Y-%m-%d"),
        "entries": clean,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    text = _WORKSHEET_HEADER.format(corpus=corpus) + yaml.dump(
        body, allow_unicode=True, sort_keys=False, default_flow_style=False)
    path.write_text(text)


# -- Resolution ----------------------------------------------------------------
def _resolve_entries(entries: list[dict], metadata: dict) -> None:
    """Populate gleif_canonical/gleif_lei/status per entry.
       corrected -> deterministic by-LEI; named+uncached -> name-search guess;
       named+cached -> keep; name-less -> needs identity."""
    total = len(entries)
    for i, e in enumerate(entries, 1):
        label = e.get("xbrl_name") or f"[group {e.get('group_key', '?')}]"
        print("\r" + f"  ▶ Resolving {i}/{total} — {label}"[:100] + "\033[K",
              end="", flush=True)

        corrected = (e.get("lei_corrected") or "").strip()
        if corrected:
            rec = kb._fetch_gleif_by_lei(corrected, metadata)
            if rec:
                e["gleif_canonical"] = rec["canonical"]
                e["gleif_lei"] = rec["lei"]
                e["status"] = "corrected"
            else:
                e["status"] = "lei_corrected_invalid"
            continue

        name = (e.get("xbrl_name") or "").strip()
        if not name:
            e["status"] = "needs_identity"
            continue

        if e.get("gleif_lei"):           # cached guess from a prior pass — don't re-fetch
            e["status"] = e.get("status") or "guessed"
            continue

        rec = kb._fetch_gleif_entity(name, metadata, common_name=name)
        if rec and rec.get("lei"):
            e["gleif_canonical"] = rec["canonical"]
            e["gleif_lei"] = rec["lei"]
            e["status"] = "guessed"
        else:
            e["status"] = "unresolved"

    done = sum(1 for e in entries if e.get("gleif_lei"))
    print("\r" + f"  ✅ Resolved {done}/{total} entr(y/ies) (corrected + guessed)." + "\033[K")


# -- Review --------------------------------------------------------------------
def _review(entries: list[dict]) -> None:
    print("--- Review")
    named = [e for e in entries if e.get("xbrl_name")]
    groups = [e for e in entries if not e.get("xbrl_name")]
    by_status: dict[str, list[dict]] = {}
    for e in named:
        by_status.setdefault(e.get("status", "guessed"), []).append(e)

    print(f"  {len(named)} named entr(y/ies), {len(groups)} name-less group(s)\n")

    order = ["corrected", "guessed", "unresolved", "lei_corrected_invalid"]
    marks = {"corrected": "✅", "guessed": "·", "unresolved": "❌",
             "lei_corrected_invalid": "❌"}
    for status in order:
        for e in by_status.get(status, []):
            mark = marks.get(status, "·")
            canon = e.get("gleif_canonical") or "(unresolved)"
            lei = e.get("gleif_lei") or "—"
            tag = "  ← lei_corrected" if status == "corrected" else ""
            if status == "lei_corrected_invalid":
                tag = "  ⚠ lei_corrected not found in GLEIF"
            print(f"  {mark} {canon}{tag}")
            print(f"      LEI {lei} · {len(e.get('files', []))} file(s) "
                  f"· xbrl_name \"{e.get('xbrl_name')}\"")
    if groups:
        print(f"\n  ⚠ {len(groups)} name-less group(s) — author an xbrl_name (or canonical) "
              f"in the worksheet so these can be ingested:")
        for e in groups:
            authored = " (canonical authored)" if e.get("canonical") else ""
            files = e.get("files", [])
            print(f"      [{e.get('group_key')}]  {len(files)} file(s)"
                  f"{authored}: {', '.join(files[:3])}"
                  + (" …" if len(files) > 3 else ""))
    print()


# -- KB build (--apply) --------------------------------------------------------
def _entries_to_kb(entries: list[dict], metadata: dict):
    """Build the xbrl_name-keyed KB index from corrected entries.
    Returns (index, lei_groups, unbindable)."""
    lei_groups: dict[str, dict] = {}
    index: dict[str, dict] = {}
    unbindable: list[dict] = []
    for e in entries:
        name = (e.get("xbrl_name") or "").strip()
        lei = (e.get("lei_corrected") or e.get("gleif_lei") or "").strip()
        canon = e.get("gleif_canonical") or e.get("canonical")
        if not name or not lei or not canon:
            unbindable.append(e)
            continue
        if lei not in lei_groups:
            lei_groups[lei] = {"canonical": canon, "lei": lei,
                               "scope_name": name, "aliases": [], "xbrl_names": []}
        lei_groups[lei]["xbrl_names"].append(name)
        index[name] = {"canonical": canon, "lei": lei, "aliases": []}

    if lei_groups:
        kb._enrich_aliases(list(lei_groups.values()), [])
        lei_alias = {lei: g.get("aliases", []) for lei, g in lei_groups.items()}
        for rec in index.values():
            rec["aliases"] = list(lei_alias.get(rec["lei"], []))   # copy → no YAML anchors
    return index, lei_groups, unbindable


def _write_kb(corpus: str, index: dict, lei_groups: dict, unbindable: list[dict]) -> Path:
    out_dir = kb.KNOWLEDGE_SOURCES_DIR / "gleif"
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"gleif_{corpus}_full_entities.yaml"
    content = {
        "schema_version": "2.0",
        "source_id": "gleif",
        "corpus": corpus,
        "scope_id": "full",
        "generated": kb.datetime.now().strftime("%Y-%m-%d"),
        "entity_count": len(lei_groups),
        "key_count": len(index),
        "unbindable_count": len(unbindable),
        "xbrl_index": index,
    }
    with open(path, "w") as f:
        yaml.dump(content, f, allow_unicode=True, sort_keys=False, default_flow_style=False)
    return path


# -- Orchestration -------------------------------------------------------------
def _build(corpus: str, apply: bool, rescan: bool) -> int:
    wpath = _worksheet_path(corpus)
    metadata = kb._load_metadata("gleif")

    if not wpath.exists() or rescan:
        print("--- Scan")
        fresh = _scan_to_entries(corpus)
        if not fresh:
            kb._err(f"No filings found in data/corpora/{corpus}/uploads/")
            return 1
        if rescan and wpath.exists():
            fresh = _merge_edits(fresh, _load_worksheet(wpath))
            print("  · merged — preserved lei_corrected + authored names from prior worksheet")
        named = sum(1 for e in fresh if e.get("xbrl_name"))
        groups = sum(1 for e in fresh if not e.get("xbrl_name"))
        print(f"  · {corpus}: {named} named entr(y/ies), {groups} name-less group(s)")
        print("--- Resolve")
        _resolve_entries(fresh, metadata)
        _write_worksheet(corpus, wpath, fresh)
        _review(fresh)
        if apply:
            print("· A worksheet was just generated — review it first, then re-run with --apply.")
        print(f"· Worksheet written → {wpath.relative_to(kb.REPO)}")
        print("· Edit `lei_corrected` (and xbrl_name for name-less groups), then re-run.")
        return 0

    # Worksheet exists → consume edits.
    print("--- Worksheet")
    entries = _load_worksheet(wpath)
    print(f"  · loaded {len(entries)} entr(y/ies) from {wpath.relative_to(kb.REPO)}")
    print("--- Resolve")
    _resolve_entries(entries, metadata)
    _write_worksheet(corpus, wpath, entries)   # refresh corrected canonicals
    _review(entries)

    if not apply:
        print("· Worksheet refreshed. Re-run with --apply to write the KB when the table is clean.")
        return 0

    index, lei_groups, unbindable = _entries_to_kb(entries, metadata)
    if not index:
        kb._err("Nothing bindable yet — every entry lacks a resolved LEI or an xbrl_name.")
        return 1
    path = _write_kb(corpus, index, lei_groups, unbindable)
    kb._update_catalog("gleif", corpus, "full", len(lei_groups), path)
    print(f"✅ Wrote {path.relative_to(kb.REPO)} — {len(index)} xbrl_name key(s) "
          f"→ {len(lei_groups)} entit(y/ies); {len(unbindable)} still unbindable. Catalog updated.")
    return 0


def _print_help() -> None:
    print(f"{SCRIPT_NAME} v{VERSION} — build the entity KB for a whole corpus (GLEIF)")
    print("")
    print(f"Usage: {SCRIPT_NAME} --corpus <C> [--rescan] [--apply]")
    print("")
    print("  --corpus <C>   corpus name (scans data/corpora/<C>/uploads/)")
    print("  --rescan       re-read the uploads dir and merge, keeping worksheet edits")
    print("  --apply        write the KB from the corrected worksheet (else review only)")
    print("  --list         show the import catalog")
    print("  --version / --help")
    print("")
    print("Workflow: 1st run writes data/corpora/<C>/<C>_entity_worksheet.yaml; edit")
    print("lei_corrected (and xbrl_name for name-less groups); re-run to refresh; --apply.")


def main(argv=None) -> int:
    p = argparse.ArgumentParser(prog=SCRIPT_NAME, add_help=False)
    p.add_argument("--corpus")
    p.add_argument("--rescan", action="store_true")
    p.add_argument("--apply", action="store_true")
    p.add_argument("--list", action="store_true")
    p.add_argument("--version", action="store_true")
    p.add_argument("--help", action="store_true")
    args = p.parse_args(argv)

    if args.version:
        print(f"{SCRIPT_NAME} v{VERSION}")
        return 0
    if args.help:
        _print_help()
        return 0
    if args.list:
        return kb.cmd_list(SCRIPT_NAME, VERSION)
    if not args.corpus:
        kb._err("--corpus is required")
        _print_help()
        return 2
    return _build(args.corpus, args.apply, args.rescan)


if __name__ == "__main__":
    sys.exit(main())
