#!/usr/bin/env python3
# update_demo_corpus_ops.py — AIStudio Demo Corpus Updater (Operator only)
# Version: 1.0.0
# Rewrite of ais_update_demo_ops.sh logic in Python for reliability.
# Called by ais_update_demo_ops.sh wrapper.
#
# Usage:
#   python3 update_demo_corpus_ops.py [--rebuild] [--meta-only] [--verbose] [--repo-root PATH]

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
from datetime import date
from pathlib import Path

import requests
import yaml

# ── ANSI helpers ─────────────────────────────────────────────────────────────
BOLD = "\033[1m"
RESET = "\033[0m"
DIM = "\033[2m\033[3m"


def _sep(title: str) -> None:
    print(f"\n{DIM}── {title} {'─' * max(0, 52 - len(title))}{RESET}")


def _ok(msg: str) -> None:
    print(f"  ✅ {msg}")


def _info(msg: str) -> None:
    print(f"  ℹ  {msg}")


def _warn(msg: str) -> None:
    print(f"  ⚠  {msg}")


def _add(msg: str) -> None:
    print(f"  +  {msg}")


def _trash(msg: str) -> None:
    print(f"  ·  Trashed: {msg}")


def _fail(msg: str) -> None:
    print(f"❌ {msg}")
    sys.exit(1)


# ── Repo root ─────────────────────────────────────────────────────────────────
def find_repo_root(start: Path) -> Path:
    for p in [start, *start.parents]:
        if (p / ".git").exists():
            return p
    return start


# ── MD5 hash ──────────────────────────────────────────────────────────────────
def _md5(path: Path) -> str:
    h = hashlib.md5()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(65536), b""):
            h.update(block)
    return h.hexdigest()


# ── Questions deploy ──────────────────────────────────────────────────────────
def deploy_questions(seed: Path, dest: Path, force: bool = False) -> None:
    if not seed.exists():
        _warn(f"Questions seed not found: {seed} — skipping.")
        return
    seed_hash = _md5(seed)
    dest_hash = _md5(dest) if dest.exists() else ""
    if not force and seed_hash == dest_hash:
        _info("Questions unchanged — skipping. Use --force to redeploy.")
        return
    dest.parent.mkdir(parents=True, exist_ok=True)
    ver_match = re.search(r"^# Version:\s*(.+)$", seed.read_text(), re.MULTILINE)
    ver = ver_match.group(1).strip() if ver_match else "1.0.0"
    lines = [
        "# AIStudio — Demo Corpus Benchmark Questions",
        f"# Version: {ver}",
        "# Generated by ais_update_demo_ops from _demo_questions_seed_ops.yaml",
        "# Corpus: demo — 20 years of original thought leadership",
        "",
    ]
    body = "\n".join(
        line for line in seed.read_text().splitlines() if not line.startswith("#")
    ).strip()
    dest.write_text("\n".join(lines) + "\n" + body + "\n")
    _ok("demo_questions.yaml deployed from seed.")


# ── Metadata seed ─────────────────────────────────────────────────────────────
def seed_metadata(seed_info: Path, meta_file: Path) -> None:
    with open(seed_info) as f:
        seed = yaml.safe_load(f)
    runtime = {}
    if meta_file.exists():
        with open(meta_file) as f:
            existing = yaml.safe_load(f) or {}
        for field in (
            "last_ingested_at",
            "last_ingest_chunks",
            "last_ingest_files",
            "ingest_duration_seconds",
        ):
            if field in existing:
                runtime[field] = existing[field]
    meta = {
        "schema_version": "1.0",
        "corpus_name": seed.get("corpus_name", "demo"),
        "last_updated": date.today().isoformat(),
        "short_description": seed.get("short_description", ""),
        "description": seed.get("description", ""),
        "content_summary": seed.get("content_summary", ""),
        "search_guidance": seed.get("search_guidance", ""),
    }
    meta.update(runtime)
    meta_file.parent.mkdir(parents=True, exist_ok=True)
    with open(meta_file, "w") as f:
        f.write("# demo_corpus_metadata.yaml\n")
        f.write("# Corpus metadata — loaded by api.py at query time\n\n")
        yaml.dump(meta, f, allow_unicode=True, default_flow_style=False, sort_keys=False)
    _ok("demo_corpus_metadata.yaml seeded.")


# ── Sync seed_data → uploads ──────────────────────────────────────────────────
def sync_uploads(seed_data: Path, uploads: Path, trash: Path) -> tuple[int, int, int]:
    uploads.mkdir(parents=True, exist_ok=True)
    trash.mkdir(parents=True, exist_ok=True)
    added = trashed = skipped = 0
    seed_files = {f.name for f in seed_data.glob("*.pdf") if "epaves" not in str(f)}
    for f in seed_data.glob("*.pdf"):
        if "epaves" in str(f):
            continue
        dest = uploads / f.name
        if not dest.exists():
            shutil.copy2(f, dest)
            _add(f.name)
            added += 1
        else:
            skipped += 1
    for f in uploads.glob("*.pdf"):
        if f.name not in seed_files:
            shutil.move(str(f), trash / f.name)
            _trash(f.name)
            trashed += 1
    print(f"  · Added: {added}  |  Trashed: {trashed}  |  Unchanged: {skipped}")
    return added, trashed, skipped


# ── Rebuild uploads ───────────────────────────────────────────────────────────
def rebuild_uploads(seed_data: Path, uploads: Path) -> int:
    if uploads.exists():
        shutil.rmtree(uploads)
        _ok("uploads/ wiped.")
    uploads.mkdir(parents=True, exist_ok=True)
    count = 0
    for f in seed_data.glob("*.pdf"):
        if "epaves" in str(f):
            continue
        shutil.copy2(f, uploads / f.name)
        count += 1
    _ok(f"{count} PDFs copied to uploads/")
    return count


# ── API helpers ───────────────────────────────────────────────────────────────
def _api(method: str, url: str, **kwargs) -> requests.Response:
    try:
        return requests.request(method, url, timeout=10, **kwargs)
    except Exception as e:
        raise SystemExit(f"❌ API error: {e}") from None


def check_backend(api: str) -> bool:
    try:
        r = requests.get(f"{api}/health", timeout=5)
        return r.ok
    except Exception:
        return False


def ensure_corpus(api: str, corpus: str) -> None:
    r = _api("GET", f"{api}/corpus/{corpus}/info")
    if r.status_code == 404:
        print(f"  ▶ {corpus} corpus not found — creating...")
        r2 = _api("POST", f"{api}/corpus/create", json={"name": corpus})
        if r2.status_code in (200, 201):
            _ok(f"{corpus} corpus created.")
        else:
            _fail(f"Could not create {corpus} corpus (status {r2.status_code})")
    else:
        _ok(f"{corpus} corpus exists.")


def delete_corpus(api: str, corpus: str) -> None:
    r = _api("DELETE", f"{api}/corpus/{corpus}")
    if r.status_code in (200, 204, 404):
        _ok("Qdrant collection cleared.")
    else:
        _warn(f"Delete returned {r.status_code} — proceeding anyway.")


# ── Ingest ────────────────────────────────────────────────────────────────────
def run_ingest(repo: Path, corpus: str, uploads: Path, force: bool, verbose: bool) -> None:
    cmd = [
        str(repo / ".venv/bin/python3"),
        "-m",
        "local_llm_bot.app.ingest",
        "--corpus",
        corpus,
        "--root",
        str(uploads),
    ]
    if force:
        cmd.append("--force")

    env = os.environ.copy()
    env["AISTUDIO_VECTORSTORE"] = "qdrant"
    env["PYTHONPATH"] = str(repo / "src")

    if verbose:
        # Stream stderr (tqdm) live to terminal, capture stdout (JSON) separately
        proc = subprocess.Popen(
            cmd,
            cwd=str(repo),
            env=env,
            stdout=subprocess.PIPE,
            stderr=None,  # stderr goes to terminal
        )
        stdout_data, _ = proc.communicate()
    else:
        proc = subprocess.Popen(
            cmd,
            cwd=str(repo),
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
        )
        stdout_data, _ = proc.communicate()

    # Parse JSON summary from stdout
    output = stdout_data.decode("utf-8", errors="replace") if stdout_data else ""
    matches = list(re.finditer(r"^\{", output, re.MULTILINE))
    found = False
    for m in reversed(matches):
        try:
            d = json.loads(output[m.start() :])
            r = d.get("result", {})
            dur = d.get("duration_sec", 0)
            _ok(f"Ingest complete in {dur:.1f}s")
            print(f"  · Chunks written : {r.get('chunks_written', 0)}")
            print(f"  · Files processed: {r.get('files_processed', 0)}")
            print(f"  · Files skipped  : {r.get('files_skipped_unchanged', 0)}  (unchanged)")
            failed = r.get("files_failed", 0)
            if failed:
                _warn(f"Files failed: {failed}")
            found = True
            break
        except Exception:
            pass
    if not found:
        _warn("Could not parse ingest result.")


# ── Main ──────────────────────────────────────────────────────────────────────
def main() -> None:
    ap = argparse.ArgumentParser(prog="update_demo_corpus_ops")
    ap.add_argument("--rebuild", action="store_true")
    ap.add_argument("--meta-only", action="store_true", dest="meta_only")
    ap.add_argument("--verbose", action="store_true")
    ap.add_argument(
        "--force", action="store_true", help="Force redeploy questions even if unchanged"
    )
    ap.add_argument("--repo-root", default=None)
    args = ap.parse_args()

    repo = Path(args.repo_root) if args.repo_root else find_repo_root(Path(__file__))
    api = "http://localhost:8000"

    seed_data = repo / "meta/_special_corpus_seed_info/demo/seed_data"
    seed_info = repo / "meta/_special_corpus_seed_info/demo/_demo_metadata_seed_ops.yaml"
    questions_seed = repo / "meta/_special_corpus_seed_info/demo/_demo_questions_seed_ops.yaml"
    questions_dest = repo / "benchmarks/demo/demo_questions.yaml"
    uploads = repo / "data/corpora/demo/uploads"
    trash = repo / "data/corpora/demo/uploads/trash"
    meta_file = repo / "data/corpora/demo/demo_corpus_metadata.yaml"

    # Preflight
    if not seed_data.exists():
        _fail(f"Seed data directory not found: {seed_data}")
    if not seed_info.exists():
        _fail(f"Seed info file not found: {seed_info}")
    seed_count = len(list(seed_data.glob("*.pdf")))
    if seed_count == 0:
        _fail("No PDFs found in seed_data/ — nothing to sync.")
    _ok(f"{seed_count} source PDFs in seed_data/")

    # --meta-only
    if args.meta_only:
        _sep("Meta-only: seeding metadata and deploying questions")
        seed_metadata(seed_info, meta_file)
        deploy_questions(questions_seed, questions_dest, force=args.force)
        print("\n✅ Meta-only complete. No sync or ingest.")
        return

    # Step 1: Sync or Rebuild
    if args.rebuild:
        _sep("Step 1: Rebuild — wiping uploads/")
        rebuild_uploads(seed_data, uploads)
        added = seed_count
        trashed = skipped = 0
    else:
        _sep("Step 1: Syncing seed_data/ → uploads/")
        added, trashed, skipped = sync_uploads(seed_data, uploads, trash)

    # Step 2: Seed metadata + questions
    _sep("Step 2: Seeding corpus metadata")
    seed_metadata(seed_info, meta_file)
    deploy_questions(questions_seed, questions_dest, force=args.force)

    # Step 3: Check backend
    _sep("Step 3: Checking backend")
    if not check_backend(api):
        _warn("Backend not running — files and meta are ready.")
        print("  ℹ  Demo corpus will be ingested at next ais_start.")
        return
    _ok("Backend running.")

    # Step 4: Ensure corpus
    _sep("Step 4: Ensuring corpus exists")
    ensure_corpus(api, "demo")

    # Step 5: Ingest
    _sep("Step 5: Ingesting")
    upload_count = len(list(uploads.glob("*.pdf")))
    if args.rebuild:
        print(f"  ▶ Full re-ingest: {upload_count} PDFs (--force)...")
        # Wipe Qdrant collection first
        print("  ▶ Clearing Qdrant demo collection...")
        delete_corpus(api, "demo")
        ensure_corpus(api, "demo")
    else:
        print(f"  ▶ Incremental ingest: {upload_count} PDFs (skip-if-unchanged)...")
    run_ingest(repo, "demo", uploads, force=args.rebuild, verbose=args.verbose)

    # Summary
    _sep("Summary")
    if not args.rebuild:
        print(f"  · Sync — Added: {added}  |  Trashed: {trashed}  |  Unchanged: {skipped}")
    print("\n✅ Demo corpus updated.")


if __name__ == "__main__":
    main()
