#!/usr/bin/env python3
# update_corpus_ops.py — AIStudio Corpus Updater (Operator only)
# Version: 1.1.0
# Unified script for updating any AIStudio corpus from seed files.
# Called by ais_update_corpus_ops.sh wrapper.
#
# Corpus type is auto-detected:
#   generated — has meta/_special_corpus_seed_info/<corpus>/_<corpus>_manifest.yaml
#               → PDF generation from source .md files (e.g. help)
#   seeded    — has meta/_special_corpus_seed_info/<corpus>/seed_data/
#               → file sync from seed_data/ (e.g. demo)
#
# Usage:
#   python3 update_corpus_ops.py <corpus> [--meta-only] [--rebuild] [--verbose]
#                                         [--force] [--subject NAME] [--repo-root PATH]
#
# Principle: identical CLI options regardless of corpus type.

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
from datetime import date
from pathlib import Path
from time import time
from typing import Any

import requests
import yaml

# ── ANSI helpers ──────────────────────────────────────────────────────────────
DIM = "\033[2m\033[3m"
BOLD = "\033[1m"
RESET = "\033[0m"


def _sep(title: str) -> None:
    print(f"\n{DIM}── {title} {'─' * max(0, 52 - len(title))}{RESET}")


def _ok(msg: str) -> None:
    print(f"  ✅ {msg}")


def _info(msg: str) -> None:
    print(f"  ℹ  {msg}")


def _warn(msg: str) -> None:
    print(f"  ⚠  {msg}")


def _add(msg: str) -> None:
    print(f"  +  {msg}")


def _trash(msg: str) -> None:
    print(f"  ·  Trashed: {msg}")


def _fail(msg: str) -> None:
    print(f"❌ {msg}")
    sys.exit(1)


# ── Repo root ─────────────────────────────────────────────────────────────────
def find_repo_root(start: Path) -> Path:
    for p in [start, *start.parents]:
        if (p / ".git").exists():
            return p
    return start


# ── MD5 ───────────────────────────────────────────────────────────────────────
def _md5(path: Path) -> str:
    h = hashlib.md5()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(65536), b""):
            h.update(block)
    return h.hexdigest()


# ── Corpus type detection ─────────────────────────────────────────────────────
def detect_corpus_type(repo: Path, corpus: str, seed: dict) -> str:
    """
    Returns 'generated' or 'seeded' based on sources in the seed file.
    generated: source files are .md → PDF generation required
    seeded:    source files are .pdf → direct copy
    Falls back to legacy detection if no sources block.
    """
    sources = seed.get("sources", [])
    if sources:
        # Check first source that has a source_path
        for s in sources:
            sp = s.get("source_path", s.get("filename", ""))
            if sp.endswith(".md"):
                return "generated"
        return "seeded"
    # Legacy fallback
    seed_dir = repo / "meta/_special_corpus_seed_info" / corpus
    if (seed_dir / f"_{corpus}_manifest.yaml").exists():
        return "generated"
    if (seed_dir / "seed_data").exists():
        return "seeded"
    _fail(f"Cannot detect corpus type for '{corpus}'")
    return ""


# ── Questions deploy ──────────────────────────────────────────────────────────
def deploy_questions(repo: Path, corpus: str, force: bool = False) -> None:
    seed = repo / f"meta/_special_corpus_seed_info/{corpus}/_{corpus}_questions_seed_ops.yaml"
    dest = repo / f"benchmarks/{corpus}/{corpus}_questions.yaml"
    if not seed.exists():
        _info(f"No questions seed found for '{corpus}' — skipping.")
        return
    seed_hash = _md5(seed)
    dest_hash = _md5(dest) if dest.exists() else ""
    if not force and seed_hash == dest_hash:
        _info("Questions unchanged — skipping. Use --force to redeploy.")
        return
    dest.parent.mkdir(parents=True, exist_ok=True)
    ver_match = re.search(r"^# Version:\s*(.+)$", seed.read_text(), re.MULTILINE)
    ver = ver_match.group(1).strip() if ver_match else "1.0.0"
    corpus_label = {
        "help": "AIStudio documentation PDFs",
        "demo": "20 years of original thought leadership",
    }.get(corpus, corpus)
    lines = [
        f"# AIStudio — {corpus.title()} Corpus Benchmark Questions",
        f"# Version: {ver}",
        f"# Generated by ais_update_corpus_ops from _{corpus}_questions_seed_ops.yaml",
        f"# Corpus: {corpus} — {corpus_label}",
        "",
    ]
    body = "\n".join(ln for ln in seed.read_text().splitlines() if not ln.startswith("#")).strip()
    dest.write_text("\n".join(lines) + "\n" + body + "\n")
    _ok(f"{corpus}_questions.yaml deployed from seed.")


# ── Metadata seed ─────────────────────────────────────────────────────────────
def seed_metadata(
    repo: Path, corpus: str, corpus_type: str, sources_from_ingest: list[dict] | None = None
) -> None:
    seed_info = repo / f"meta/_special_corpus_seed_info/{corpus}/_{corpus}_metadata_seed_ops.yaml"
    meta_file = repo / f"data/corpora/{corpus}/{corpus}_corpus_metadata.yaml"
    if not seed_info.exists():
        _warn(f"Metadata seed not found: {seed_info} — skipping.")
        return

    with open(seed_info) as f:
        seed = yaml.safe_load(f)

    # Preserve runtime fields written by ingest pipeline
    runtime: dict[str, Any] = {}
    if meta_file.exists():
        with open(meta_file) as f:
            existing = yaml.safe_load(f) or {}
        for field in (
            "last_ingested_at",
            "last_ingest_chunks",
            "last_ingest_files",
            "ingest_duration_seconds",
        ):
            if field in existing:
                runtime[field] = existing[field]
        # Preserve existing sources if not being updated
        if sources_from_ingest is None and "sources" in existing:
            runtime["sources"] = existing["sources"]

    meta: dict[str, Any] = {
        "schema_version": "2.0",
        "corpus_name": seed.get("corpus_name", corpus),
        "corpus_type": corpus_type,
        "last_updated": date.today().isoformat(),
        "short_description": seed.get("short_description", ""),
        "description": seed.get("description", ""),
        "content_summary": seed.get("content_summary", ""),
        "search_guidance": seed.get("search_guidance", ""),
    }
    meta.update(runtime)

    # Build sources block from manifest (generated) or seed (seeded)
    if sources_from_ingest is not None:
        meta["sources"] = sources_from_ingest
    elif "sources" not in meta:
        meta["sources"] = _build_sources_block(repo, corpus, corpus_type, seed)

    meta_file.parent.mkdir(parents=True, exist_ok=True)
    with open(meta_file, "w") as f:
        f.write(f"# {corpus}_corpus_metadata.yaml\n")
        f.write("# Corpus metadata — loaded by api.py at query time\n")
        f.write(
            "# User-editable: short_description, description, search_guidance, sources[].description, sources[].keywords\n\n"
        )
        yaml.dump(meta, f, allow_unicode=True, default_flow_style=False, sort_keys=False)
    _ok(f"{corpus}_corpus_metadata.yaml seeded.")


def _build_sources_block(repo: Path, corpus: str, corpus_type: str, seed: dict) -> list[dict]:
    """Build sources[] block — use seed sources[] if present, else fall back to legacy."""
    if seed.get("sources"):
        return seed["sources"]
    # Legacy fallback for corpora without sources[] in seed
    sources = []
    default_src = seed.get(
        "default_source_path", f"meta/_special_corpus_seed_info/{corpus}/seed_data"
    )
    seed_data = Path(default_src) if Path(default_src).is_absolute() else repo / default_src
    if seed_data.exists():
        for pdf in sorted(seed_data.glob("*.pdf")):
            sources.append(
                {
                    "filename": pdf.name,
                    "description": "",
                    "keywords": [],
                }
            )
    return sources


# ── API helpers ───────────────────────────────────────────────────────────────
def check_backend(api: str) -> bool:
    try:
        return requests.get(f"{api}/health", timeout=5).ok
    except Exception:
        return False


def ensure_corpus(api: str, corpus: str) -> None:
    try:
        r = requests.get(f"{api}/corpus/{corpus}/info", timeout=10)
        if r.status_code == 404:
            print(f"  ▶ {corpus} corpus not found — creating...")
            r2 = requests.post(f"{api}/corpus/create", json={"name": corpus}, timeout=10)
            if r2.status_code in (200, 201):
                _ok(f"{corpus} corpus created.")
            else:
                _fail(f"Could not create {corpus} corpus (status {r2.status_code})")
        else:
            _ok(f"{corpus} corpus exists.")
    except Exception as e:
        _fail(f"API error checking corpus: {e}")


def delete_corpus_collection(api: str, corpus: str) -> None:
    try:
        r = requests.delete(f"{api}/corpus/{corpus}", timeout=10)
        if r.status_code in (200, 204, 404):
            _ok("Qdrant collection cleared.")
        else:
            _warn(f"Delete returned {r.status_code} — proceeding anyway.")
    except Exception as e:
        _warn(f"Delete failed: {e} — proceeding.")


# ── Ingest ────────────────────────────────────────────────────────────────────
def run_ingest(repo: Path, corpus: str, root: Path, force: bool, verbose: bool) -> None:
    cmd = [
        str(repo / ".venv/bin/python3"),
        "-m",
        "local_llm_bot.app.ingest",
        "--corpus",
        corpus,
        "--root",
        str(root),
    ]
    if force:
        cmd.append("--force")
    env = os.environ.copy()
    env["AISTUDIO_VECTORSTORE"] = "qdrant"
    env["PYTHONPATH"] = str(repo / "src")

    stderr = None if verbose else subprocess.DEVNULL
    proc = subprocess.Popen(cmd, cwd=str(repo), env=env, stdout=subprocess.PIPE, stderr=stderr)
    stdout, _ = proc.communicate()
    output = stdout.decode("utf-8", errors="replace") if stdout else ""

    matches = list(re.finditer(r"^\{", output, re.MULTILINE))
    found = False
    for m in reversed(matches):
        try:
            d = json.loads(output[m.start() :])
            r = d.get("result", {})
            dur = d.get("duration_sec", 0)
            _ok(f"Ingest complete in {dur:.1f}s")
            print(f"  · Chunks written : {r.get('chunks_written', 0)}")
            print(f"  · Files processed: {r.get('files_processed', 0)}")
            print(f"  · Files skipped  : {r.get('files_skipped_unchanged', 0)}  (unchanged)")
            failed = r.get("files_failed", 0)
            if failed:
                _warn(f"Files failed: {failed}")
            found = True
            break
        except Exception:
            pass
    if not found:
        _warn("Could not parse ingest result.")


# ── Step 1: Generated corpus (help) ──────────────────────────────────────────
def step1_generated(repo: Path, corpus: str, python: Path, seed: dict, subject: str | None) -> int:
    """Generate PDFs from source MD files listed in seed sources[].
    Resolves: default_source_path / source_path → WeasyPrint → uploads/"""
    pdf_script = repo / "scripts/update_help_corpus_ops.py"
    if not pdf_script.exists():
        _fail(f"PDF generation script not found: {pdf_script}\n· Run: ais_restore_scripts")

    # Pass subject if specified — update_help_corpus_ops.py handles per-subject generation
    cmd = [str(python), str(pdf_script), "--repo-root", str(repo)]
    if subject:
        cmd += ["--subject", subject]
    result = subprocess.run(cmd, cwd=str(repo))

    uploads = repo / f"data/corpora/{corpus}/uploads"
    pdf_count = len(list(uploads.glob("*.pdf")))

    if result.returncode != 0:
        # WeasyPrint segfaults on Apple Silicon after success (AIStudio_308)
        if pdf_count == 0:
            _fail("PDF generation failed — aborting.")
        _info(
            f"WeasyPrint exited with code {result.returncode} — PDFs verified present, continuing."
        )

    if pdf_count == 0:
        _fail("No PDFs in uploads/ — generation failed.")

    _ok(f"{pdf_count} PDFs ready in uploads/")

    # Show PDF status
    print("\n  · PDF status:")
    now = time()
    for pdf in sorted(uploads.glob("*.pdf")):
        age = now - pdf.stat().st_mtime
        status = "regenerated" if age < 120 else f"unchanged, {int(age)}s old"
        icon = "✅" if age < 120 else "ℹ "
        print(f"    {icon} {pdf.name}  ({status})")

    return pdf_count


# ── Step 1: Seeded corpus (demo) ──────────────────────────────────────────────
def step1_seeded(repo: Path, corpus: str, seed: dict, rebuild: bool) -> tuple[int, int, int, int]:
    """Sync default_source_path → uploads/. Returns (seed_count, added, trashed, skipped)."""
    default_src = seed.get(
        "default_source_path", f"meta/_special_corpus_seed_info/{corpus}/seed_data"
    )
    seed_data = Path(default_src) if Path(default_src).is_absolute() else repo / default_src
    uploads = repo / f"data/corpora/{corpus}/uploads"
    trash = repo / f"data/corpora/{corpus}/uploads/trash"

    if not seed_data.exists():
        _fail(f"Source directory not found: {seed_data}")

    seed_pdfs = {f.name: f for f in seed_data.glob("*.pdf") if "epaves" not in str(f)}
    seed_count = len(seed_pdfs)
    if seed_count == 0:
        _fail("No PDFs found in seed_data/ — nothing to sync.")
    _ok(f"{seed_count} source PDFs in seed_data/")

    if rebuild:
        if uploads.exists():
            shutil.rmtree(uploads)
            _ok("uploads/ wiped.")
        uploads.mkdir(parents=True, exist_ok=True)
        for f in seed_pdfs.values():
            shutil.copy2(f, uploads / f.name)
        _ok(f"{seed_count} PDFs copied to uploads/")
        return seed_count, seed_count, 0, 0

    uploads.mkdir(parents=True, exist_ok=True)
    trash.mkdir(parents=True, exist_ok=True)
    added = trashed = skipped = 0

    for name, src in sorted(seed_pdfs.items()):
        dest = uploads / name
        if not dest.exists():
            shutil.copy2(src, dest)
            _add(name)
            added += 1
        else:
            skipped += 1

    for f in uploads.glob("*.pdf"):
        if f.name not in seed_pdfs:
            shutil.move(str(f), trash / f.name)
            _trash(f.name)
            trashed += 1

    print(f"  · Added: {added}  |  Trashed: {trashed}  |  Unchanged: {skipped}")
    return seed_count, added, trashed, skipped


# ── Surgical ingest (generated corpora only) ──────────────────────────────────
def run_surgical_ingest(repo: Path, corpus: str, api: str, subject: str, verbose: bool) -> None:
    manifest_path = repo / f"meta/_special_corpus_seed_info/{corpus}/_{corpus}_manifest.yaml"
    subject_pdf = None
    if manifest_path.exists():
        with open(manifest_path) as f:
            manifest = yaml.safe_load(f)
        for s in manifest.get("subjects", []):
            if s.get("subject") == subject:
                subject_pdf = Path(s.get("corpus_path", s.get("pdf", ""))).name
                break

    if not subject_pdf:
        _warn(f"Could not resolve PDF for subject '{subject}' — falling back to full ingest.")
        uploads = repo / f"data/corpora/{corpus}/uploads"
        run_ingest(repo, corpus, uploads, force=True, verbose=verbose)
        return

    print(f"  ▶ Surgical re-ingest: {subject_pdf}...")
    try:
        from urllib.parse import quote

        r = requests.delete(f"{api}/corpus/{corpus}/file/{quote(subject_pdf)}", timeout=30)
        if r.status_code in (200, 404):
            _ok("Existing chunks removed (or file not yet indexed).")
        else:
            _warn(f"Delete returned {r.status_code} — proceeding.")
    except Exception as e:
        _warn(f"Delete failed: {e} — proceeding.")

    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        src = repo / f"data/corpora/{corpus}/uploads" / subject_pdf
        shutil.copy2(src, Path(tmp) / subject_pdf)
        run_ingest(repo, corpus, Path(tmp), force=False, verbose=verbose)


# ── Main ──────────────────────────────────────────────────────────────────────
def main() -> None:
    ap = argparse.ArgumentParser(
        prog="update_corpus_ops", description="Update any AIStudio corpus from seed files"
    )
    ap.add_argument("corpus", help="Corpus name (e.g. help, demo)")
    ap.add_argument(
        "--meta-only",
        action="store_true",
        dest="meta_only",
        help="Deploy metadata + questions only — no file sync or ingest",
    )
    ap.add_argument(
        "--rebuild",
        action="store_true",
        help="Wipe uploads/ and Qdrant, re-ingest everything (seeded corpora)",
    )
    ap.add_argument("--verbose", action="store_true", help="Show live ingest progress bars")
    ap.add_argument(
        "--force", action="store_true", help="Force redeploy questions even if seed unchanged"
    )
    ap.add_argument(
        "--subject",
        default=None,
        help="Regenerate + surgical re-ingest one subject only (generated corpora)",
    )
    ap.add_argument("--repo-root", default=None)
    args = ap.parse_args()

    corpus = args.corpus
    repo = Path(args.repo_root) if args.repo_root else find_repo_root(Path(__file__))
    api = "http://localhost:8000"
    python = repo / ".venv/bin/python3"

    if not python.exists():
        _fail(f"Python venv not found: {python}")

    # Load seed file early — needed for corpus type detection
    seed_info = repo / f"meta/_special_corpus_seed_info/{corpus}/_{corpus}_metadata_seed_ops.yaml"
    if not seed_info.exists():
        _fail(f"Seed file not found: {seed_info}")
    with open(seed_info) as f:
        _seed_data = yaml.safe_load(f) or {}
    corpus_type = detect_corpus_type(repo, corpus, _seed_data)

    print(f"\n{DIM}corpus: {corpus}  |  type: {corpus_type}{RESET}")

    # ── --meta-only ───────────────────────────────────────────────────────────
    if args.meta_only:
        _sep("Meta-only: seeding metadata and deploying questions")
        seed_metadata(repo, corpus, corpus_type)  # seed already loaded above
        deploy_questions(repo, corpus, force=args.force)
        print("\n✅ Meta-only complete. No sync or ingest.")
        return

    # ── Step 1: Sync or generate files ───────────────────────────────────────
    file_count = 0
    added = trashed = skipped = 0

    if corpus_type == "generated":
        _sep("Step 1: Generating PDFs and seeding corpus metadata")
        file_count = step1_generated(repo, corpus, python, _seed_data, args.subject)
    elif corpus_type == "seeded":
        if args.rebuild:
            _sep("Step 1: Rebuild — wiping uploads/")
        else:
            _sep("Step 1: Syncing seed_data/ → uploads/")
        seed_count, added, trashed, skipped = step1_seeded(repo, corpus, _seed_data, args.rebuild)
        file_count = seed_count

    # ── Step 2: Seed metadata + questions ────────────────────────────────────
    _sep("Step 2: Seeding corpus metadata")
    seed_metadata(repo, corpus, corpus_type)  # seed already loaded above
    deploy_questions(repo, corpus, force=args.force)

    # ── Step 3: Check backend ─────────────────────────────────────────────────
    _sep("Step 3: Checking backend")
    if not check_backend(api):
        _warn("Backend not running — files and meta are ready.")
        print(f"  ℹ  {corpus} corpus will be ingested at next ais_start.")
        return
    _ok("Backend running.")

    # ── Step 4: Ensure corpus ─────────────────────────────────────────────────
    _sep("Step 4: Ensuring corpus exists")
    if args.rebuild and corpus_type == "seeded":
        print("  ▶ Clearing Qdrant collection...")
        delete_corpus_collection(api, corpus)
    ensure_corpus(api, corpus)

    # ── Step 5: Ingest ────────────────────────────────────────────────────────
    _sep("Step 5: Ingesting")
    uploads = repo / f"data/corpora/{corpus}/uploads"
    upload_count = len(list(uploads.glob("*.*")))

    if corpus_type == "generated" and args.subject:
        run_surgical_ingest(repo, corpus, api, args.subject, args.verbose)
    elif corpus_type == "generated":
        print(f"  ▶ Ingesting {file_count} PDFs (--force)...")
        run_ingest(repo, corpus, uploads, force=True, verbose=args.verbose)
    elif corpus_type == "seeded":
        mode = "full re-ingest (--force)" if args.rebuild else "incremental (skip-if-unchanged)"
        print(f"  ▶ {upload_count} PDFs — {mode}...")
        run_ingest(repo, corpus, uploads, force=args.rebuild, verbose=args.verbose)

    # ── Summary ───────────────────────────────────────────────────────────────
    _sep("Summary")
    if corpus_type == "seeded" and not args.rebuild:
        print(f"  · Sync — Added: {added}  |  Trashed: {trashed}  |  Unchanged: {skipped}")
    print(f"\n✅ {corpus} corpus updated.")


if __name__ == "__main__":
    main()
